sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler || gem install bundler -v 1.17.3
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.2
# Put this in your .travis.yml
gemfile:
  - gemfiles/rubocop_0.60.gemfile
  - gemfiles/rubocop_0.61.gemfile
  - gemfiles/rubocop_0.62.gemfile
  - gemfiles/rubocop_0.63.gemfile
  - gemfiles/rubocop_0.64.gemfile
  - gemfiles/rubocop_0.65.gemfile
  - gemfiles/rubocop_0.66.gemfile
